print("Which restaurant do you wish to buy from?")
print("1.restaurant a")                                                                                                          
print("2.restaurant b")
print("3.restaurant c")
r=input()
if r=="restaurant a" or r=="1":
	print("MENU 1")
	print ("1.Hyderabadi Chicken Biriyani")
	print ("2.Mushroom Munchurian")
	print ("3.Brownie")
	print("What do you wish to buy?")
	file=open("restaurant a.txt","a")
	file.write("\n")
	file.write("Your order is: ")
	y=input()
	file.write(y)
	print("Do you wish to keep the selected meal as your favourite?")
	x=input()
	if x=="yes":
		file=open("Favourites.txt","a")
		file.write("\n")
		file.write(y)
elif r=="restaurant b" or r=="2":
	print("Menu 2")
	print ("1.Chicken Fried rice")
	print ("2.French Fries")
	print ("3.Chocolate Ice Cream")
	print("What do you wish to buy?")
	file=open("restaurant b.txt","a")
	file.write("\n")
	file.write("Your order is: ")
	q=input()
	file.write(q)
	print("Do you wish to keep the selected meal as your favourite?")
	w=input()
	if w=="yes":
		file=open("Favourites.txt","a")
		file.write("\n")
		file.write(q)
elif r=="restaurant c" or r=="3":
	print("Menu 3")
	print ("1.Butter Nun")
	print ("2.Dal Makhani")
	print ("3.Kulfi")
	print("What do you wish to buy?")
	file=open("restaurant c.txt","a")
	file.write("\n")
	file.write("your order is: ")
	o=input()
	file.write(o)
	print("Do you wish to keep the selected meal as your favourite?")
	c=input()
	if c=="yes":
		file=open("Favourites.txt","a")
		file.write("\n")
		file.write(o)